stages:
  - build
# - test

# lint:
#   image: node:20
#   stage: test
#   script:
#     - npm install
#     - npx eslint .

#test:
#  image: node:20
#  stage: test
#  script:
#    - npm install
#    - npm run test -- --watchAll=false

deploy:
  stage: build
  image: docker:latest
# when: manual
  services:
    - docker:dind
  script:
    - ls
    - docker build -t registry.gitlab.com/alekstodelet/test-front-app .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin registry.gitlab.com
    - docker push registry.gitlab.com/alekstodelet/test-front-app
    - docker logout registry.gitlab.com
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
