import { Troubleshoot } from "@mui/icons-material";

export const mockSmProjects = {
  status: 200,
  data: [
    { id: 1, name: "test1", code: "test1", description: "test description1" },
    { id: 2, name: "test2", code: "test2", description: "test description2" },
    { id: 3, name: "test3", code: "test3", description: "test description3" },
    { id: 4, name: "test4", code: "test4", description: "test description4" },
  ],
};

export const mockSmProject = {
  status: 200,
  data: {
    id: 1,
    name: "Project 1",
    projecttype_id: 1,
    projecttype_idNavName: "Type 1",
    status_id: 1,
    status_idNavName: "Status 1",
    test: true,
    min_responses: 5,
    date_end: "2024-08-16T23:30:00",
    access_link: "http://example.com",
    entity_id: 1,
    entity_idNavName: "Entity 1",
    frequency_id: 2,
    frequency_idNavName: "Frequency 1",
    is_triggers_required: false,
    date_attribute_milestone_id: 3,
    date_attribute_milestone_idNavName: "Milestone 1",
  },
};

export const mockSmProjectsPagination = {
  status: 200,
  data: {
    data: [
      {
        id: 1,
        name: "Project 1",
        projecttype_idNavName: "Type 1",
        test: "Test 1",
        status_idNavName: "Status 1",
        min_responses: 5,
        date_end: "2024-01-01",
        access_link: "http://example.com",
        entity_idNavName: "Entity 1",
        frequency_idNavName: "Frequency 1",
        is_triggers_required: true,
        date_attribute_milestone_idNavName: "Milestone 1",
      },
      {
        id: 2,
        name: "Project 2",
        projecttype_idNavName: "Type 2",
        test: "Test 2",
        status_idNavName: "Status 2",
        min_responses: 10,
        date_end: "2024-02-01",
        access_link: "http://example.com",
        entity_idNavName: "Entity 2",
        frequency_idNavName: "Frequency 2",
        is_triggers_required: false,
        date_attribute_milestone_idNavName: "Milestone 2",
      },
      {
        id: 3,
        name: "Project 3",
        projecttype_idNavName: "Type 3",
        test: "Test 3",
        status_idNavName: "Status 3",
        min_responses: 15,
        date_end: "2024-03-01",
        access_link: "http://example.com",
        entity_idNavName: "Entity 3",
        frequency_idNavName: "Frequency 3",
        is_triggers_required: true,
        date_attribute_milestone_idNavName: "Milestone 3",
      },
      {
        id: 4,
        name: "Project 4",
        projecttype_idNavName: "Type 4",
        test: "Test 4",
        status_idNavName: "Status 4",
        min_responses: 20,
        date_end: "2024-04-01",
        access_link: "http://example.com",
        entity_idNavName: "Entity 4",
        frequency_idNavName: "Frequency 4",
        is_triggers_required: false,
        date_attribute_milestone_idNavName: "Milestone 4",
      },
      {
        id: 5,
        name: "Project 5",
        projecttype_idNavName: "Type 5",
        test: "Test 5",
        status_idNavName: "Status 5",
        min_responses: 25,
        date_end: "2024-05-01",
        access_link: "http://example.com",
        entity_idNavName: "Entity 5",
        frequency_idNavName: "Frequency 5",
        is_triggers_required: true,
        date_attribute_milestone_idNavName: "Milestone 5",
      },
    ],
    total_count: 5,
  },
};
